config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listitems
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listitem.rb
class Listitem < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :listitems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = "This is home page."
  end

  def about
    about = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
    @about_me = about
  end
end

app/controllers/listitems_controller.rb
class ListitemsController < ApplicationController
  before_action :set_listitem, only: %i[ show edit update destroy ]
  #before_action :authenticate_user!
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /listitems or /listitems.json
  def index
    @listitems = Listitem.all
  end

  # GET /listitems/1 or /listitems/1.json
  def show
  end

  # GET /listitems/new
  def new
    #@listitem = Listitem.new
    @listitem = current_user.listitems.build
  end

  # GET /listitems/1/edit
  def edit
  end

  # POST /listitems or /listitems.json
  def create
    #@listitem = Listitem.new(listitem_params)
    @listitem = current_user.listitems.build(listitem_params)
    respond_to do |format|
      if @listitem.save
        format.html { redirect_to @listitem, notice: "Listitem was successfully created." }
        format.json { render :show, status: :created, location: @listitem }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listitems/1 or /listitems/1.json
  def update
    respond_to do |format|
      if @listitem.update(listitem_params)
        format.html { redirect_to @listitem, notice: "Listitem was successfully updated." }
        format.json { render :show, status: :ok, location: @listitem }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listitems/1 or /listitems/1.json
  def destroy
    @listitem.destroy
    respond_to do |format|
      format.html { redirect_to listitems_url, notice: "Listitem was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user 
    @listitem  = current_user.listitems.find_by(id: params[:id])
    redirect_to listitems_path, notice: "Not Authorized To Edit This Item" if @listitem.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listitem
      @listitem = Listitem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listitem_params
      params.require(:listitem).permit(:item_name, :item_count, :item_description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listitems_helper.rb
module ListitemsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "MyApp", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "List", listitems_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>
<p><%= @about_me%></p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p><%= @home %></p>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alert' %>
      <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/listitems/_form.html.erb
<%= form_with(model: listitem) do |form| %>
  <% if listitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listitem.errors.count, "error") %> prohibited this listitem from being saved:</h2>

      <ul>
        <% listitem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :item_count %>
    <%= form.number_field :item_count, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :item_description %>
    <%= form.text_field :item_description, class:"form-control" %>
  </div>

  <div class="mb-3">
    <%= form.hidden_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/listitems/edit.html.erb
<h1>Editing Listitem</h1>
<br/>
<%= render 'form', listitem: @listitem %>
<br />
<%= link_to 'Show ', @listitem, class:"btn btn-secondary" %>
<%= link_to 'Delete', @listitem, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', listitems_path, class:"btn btn-secondary", style:"width:70px;" %>

app/views/listitems/index.html.erb
<% if user_signed_in?%>
<h1>List Items</h1>
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Item name</th>
      <th>Item count</th>
      <th>Item description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @listitems.each do |listitem| %>
      <% if listitem.user == current_user %>
        <tr>
          <td><%= link_to listitem.item_name, listitem %></td>
          <td><%= listitem.item_count %></td>
          <td><%= listitem.item_description %></td>
          <td><%= link_to 'Delete', listitem, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Listitem', new_listitem_path, class:"btn btn-secondary" %>
<% else %>
<h1 style="text-align:center"> Page Not Found </h1>
<% end %>

app/views/listitems/new.html.erb
<h1>Add New Item</h1>

<%= render 'form', listitem: @listitem %>

<%= link_to 'Back', listitems_path %>

app/views/listitems/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @listitem.item_name %></h1>
    <p class="col-md-8 fs-4">Count: <%= @listitem.item_count %></p>
    <p class="col-md-8 fs-4">Description: <%= @listitem.item_description %></p>
    <%= link_to 'Edit', edit_listitem_path(@listitem), class:"btn btn-secondary" %>
    <%= link_to 'Delete', @listitem, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
    <%= link_to 'Back', listitems_path, class:"btn btn-dark" %>
  </div>
</div>